
column_names:
  source_file_column: "source file"
  indications_text_column: "indications text"
  disease_list_column: "structured list"
  disease_name_column: "disease name"
  drug_name_column: "drug name"
  drug_id_column: "drug id nameres"
  drug_label_column: "drug label nameres"
  disease_id_column: "disease id nameres"
  disease_label_column: "disease label nameres"
  llm_true_false_column_disease: "llm_nameres_correct"
  nameres_options_id_column: "nameres id options disease"
  nameres_options_label_column: "nameres label options disease"
  llm_improved_id_column : "llm disease id"
  llm_normalized_id_column_disease: "final normalized disease id"
  llm_normalized_label_column_disease: "final normalized disease label"
  llm_true_false_column_drug: "llm_nameres_correct_drug"
  llm_improved_id_column_drug: "llm drug id"
  llm_normalized_id_column_drug: "final normalized drug id"
  llm_normalized_label_column_drug: "final normalized drug label"
  deduplication_column: "drug|disease"
  downfilled_true_false_column: "downfilled from mondo"
  contraindications_structured_list_column: "diseases contraindicated"
  contraindications_text_column: "contraindications"
  contraindications_active_ingredients: "active ingredient"
  new_contraindications_disease_name_column: "disease contraindicated"
  is_allergen_column: "is_allergen"
  is_diagnostic_column: "is_diagnostic_agent"
  hyperrelations_column: "hyperrelations"

pmda_mapping_columns:
  origin_string: "Active Ingredient (underlined: new active ingredient)"
  id: curie
  label: curie_label

ema_mapping_columns:
  origin_string: "Active substance"
  id: curie
  label: curie_label

biolink_type_disease: "DiseaseOrPhenotypicFeature"
biolink_type_drug: "ChemicalOrDrugOrTreatment"

path_to_fda_labels: /Volumes/MML/2025_06_30_dailymed/

structured_list_prompt: "Produce a list of diseases treated in the following therapeutic indications text. Please format the list as: 'item1|item2|...|itemN'. Do not include any other text in the response. If no diseases are treated, return 'None'. If the drug is only used for imaging, diagnostic, allergy testing, or procedural purposes (e.g., Technetium), return 'None'. Do not infer any diseases - only list diseases directly included in the passage. Be as specific as possible when naming diseases, including listing genetic condition subvariant when this information is provided. Be careful to avoid including contraindicated conditions which may be included in the text. If no text is provided, respond 'None'. START TEXT HERE:"
contraindications_structured_list_prompt: "Produce a list of contraindicated diseases in the following contraindications text. Please format the list as: 'item1|item2|...|itemN'. Do not include any other text in the response. If no contraindications, return 'None'. Do not include drug hypersensitivity. Do not infer any diseases - only list diseases directly included in the passage. If no text is provided, respond 'None'. Do not include therapeutic indications if the input text contains indications. Do not include interaction contraindications, i.e., when a drug is used concurrently with another drug. Exclude conditions related to allergy, e.g. anaphylaxis, angioedema, urticaria.  START TEXT HERE:"
indications_hyperrelations_prompt: "From the following indications text, extract each indication in JSON format along with the hyperrelational context required to understand the complete medical intent of the indication. Provide only one entry per drug-disease pair, with a list of context objects for each case contextualizing the drug-disease pair. As an example, if the indications text was \"drug X is indicated in combination with drug A for use in adult patients with late-stage disease Y with P mutation of gene Q who were previously unresponsive to treatment with drug Z\", the appropriate output would be:\"{drug\": \"X\",\"disease\":\"Y\",\"context\": [{\"patient_type\":\"adult\"},{\"stage\": \"late_stage\"},{\"previous_history\":\"unresponsive to treatment with drug Z\"},{\"coadministration\":\"A\"},{\"mutation\":\"Q\",\"mutation_type\":\"P\"}]}\"The options for hyperrelational context are: 'previous_history','patient_type','stage','coadministration','mutation / mutation_type','additional_details'. Do not infer any of these relationships and do not add them if they are not specified. For patient_type, relevant types are 'not_specified', 'adult', 'pediatric', 'pregnant', or 'of childbearing age'. \"coadministration\" does not refer to specifying whether the therapy is a first-line or adjunctive therapy but rather listing coadministered drugs if there is another drug or drug class listed as being administered together with the drug in the indications text. Do not include any indications for allergy tests, diagnostic agents, or surgical procedures. If no information is provided, return \"None\".indications text:"
gemini_env_var: "GOOGLE_API_KEY"
gemini_env_var_personal: "GEMINI_API_KEY_PERSONAL"

is_allergen_prompt: "Is the following active ingredient commonly used as an allergen for allergy testing? Respond only TRUE or FALSE. Provide no explanation. ACTIVE INGREDIENT: "
is_radiolabel_prompt: "Is the following active ingredient commonly used as a radiolabel or diagnostic agent? Respond only TRUE or FALSE. Provide no explanation. ACTIVE INGREDIENT: "

gemini_generation_config:
  - max_output_tokens: 8192
  - temperature: 0
  - top_p: 0.95

gemini_safety_setting: SafetySetting.HarmBlockThreshold.BLOCK_ONLY_HIGH

strings_to_clean_from_disease_list:
  - "LLM EXTRACTION ERROR"
  - "None "
  - "None"
  - ""
  - "none"
  - "ERROR"

cleaning_regex_sub_pattern: "[^A-Za-z0-9 ]+"


id_correct_incorrect_tag_disease:
  model_params:
    model: gpt-4o
    prompt: "Are the following concepts similar enough that they could be considered the same disease? Return only TRUE or FALSE. Provide no explanation."
    temperature: 0

id_correct_incorrect_tag_drug:
  model_params:
    model: gpt-4o
    prompt: "Are the following concepts similar enough that they could be considered the same drug? Return only TRUE or FALSE. Provide no explanation. If drug components are omitted from combination therapies, return FALSE"
    temperature: 0

llm_best_id_tag:
  output_column_name: "llm_best_id"
  model_params:
    model: gpt-4o
    prompt: "Return ONLY the best ontological ID (e.g., 'MONDO:0000001') from the following to represent the provided disease concept. Do not include the label or item number. If no matches, return NONE."
    temperature: 0

llm_best_id_tag_drug:
  output_column_name: "llm_best_id_drug"
  model_params:
    model: gpt-4o
    prompt: "Return ONLY the best ontological ID (e.g., 'PUBCHEM:00000001') from the following to represent the provided drug concept. Do not include the label or item number. If no matches, return NONE. If a combination therapy and no complete concept describing all components within the concept is available, return NONE"
    temperature: 0

orchard_asset_field_names:
  drug_field_name: drug_kg_node_id
  disease_field_name: disease_kg_node_id
  indication_field_name: indication