name: Create Release

on:
  push:
    tags:
      - 'v*.*.*' # Triggers the workflow on version tags (e.g., v1.0.0)

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Create a release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      # INDICATION LIST
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: matrix-indication-list/data/03_primary/matrix_indication_list.xlsx # Replace with the path to your file
          asset_name: indicationList.xlsx              # Replace with the name you want for the uploaded asset
          asset_content_type: application/octet-stream

      # INDICATION LIST DOWNFILLED
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: matrix-indication-list/data/03_primary/matrix_indication_list_downfilled (INFERRED RELATIONSHIPS BASED ON DISEASE SUBTYPES - NOT APPROVED BY ANY GOVERNMENT AGENCY).xlsx # Replace with the path to your file
          asset_name: indicationList_downfilled.xlsx              # Replace with the name you want for the uploaded asset
          asset_content_type: application/octet-stream

      # CONTRAINDICATION LIST
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: matrix-indication-list/data/03_primary/matrix_contraindication_list.xlsx # Replace with the path to your file
          asset_name: contraindicationList.xlsx              # Replace with the name you want for the uploaded asset
          asset_content_type: application/octet-stream

      # CONTRAINDICATION LIST DOWNFILLED
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: matrix-indication-list/data/03_primary/matrix_contraindication_list_downfilled (INFERRED RELATIONSHIPS BASED ON DISEASE SUBTYPES - NOT APPROVED BY ANY GOVERNMENT AGENCY).xlsx # Replace with the path to your file
          asset_name: contraindicationList_downfilled.xlsx              # Replace with the name you want for the uploaded asset
          asset_content_type: application/octet-stream


      - name: Upload Parquet folder
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: matrix-indication-list/data/03_primary/gt_orchard.parquet.zip # Replace with the path to your file
          asset_name: orchard_known_entities             # Replace with the name you want for the uploaded asset
          asset_content_type: application/octet-stream
